/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in many projects.
// It is committed here so TypeScript understands Next.js types from the start.
